### ISSUE TITLE
rlimit

### ISSUE THREAD

**Issue by friguzzi** [SWI-Prolog/swish#101]
`rlimit` does not seem to work:
when executing a memory hungry process I get

```
Service Unavailable
The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.

Apache/2.4.29 (Ubuntu) Server at cplint.eu Port 80
```
rather than a warning.
I tried `rlimit` also locally and I got a termination with message 
```
[FATAL ERROR: at Tue Dec  4 09:15:44 2018
	Could not allocate memory: Cannot allocate memory]
```
once and
```
Killed
```
another time.
Is it normal?

**Comment by JanWielemaker** [comment]
I don't think it works correctly.  I always had some trouble figuring out the proper limit.  I'd guess the connection tot he system call is fine.  But ..

> [FATAL ERROR: at Tue Dec 4 09:15:44 2018 Could not allocate memory: Cannot allocate memory]

is what it is expected to result in.   Next you are supposed to run the system in some environment that restarts it (like `systemd`, using an appropriate restart policy or `docker` or just a loop in a shell script)

> `Killed`

is typically what happens if the entire system is out of memory and starts killing processes to survive.

What should be done is to ensure that all cplint tasks have appropriate settings that avoid them causing  the entire process to run out of memory.  By default the stacks, temporary module size and table space is limited.  This should suffice.   Are you putting stuff somewhere else?

**Comment by friguzzi** [comment]
So the expected result of rlimit is to kill the process? I thought its use was to throw and exception and end the current goal without exiting.

As for the space used by cplint, I do some assert in the library modules (pita, mcintyre) declaring them as thread_local, are these limited as well?

**Comment by JanWielemaker** [comment]
Nope.  rlimit on memory causes malloc()/realloc() to fail AFAIK.    Limiting e.g., cputime causes a signal.  In any case, you cannot relate these to a specific thread so there is no way to take appropriate action.   You can only use rlimit to kill the entire process and prevent it from using all the hardware capabilities.

> As for the space used by cplint, I do some assert in the library modules (pita, mcintyre) declaring them as thread_local, are these limited as well?

By default there is no limit on the size of modules.   So yes, this might be your problem.  I guess the solution that is most consistent with SWISH' design is to store this in the working module.   Alternatively we could consider adding a limit to thread-local store.  Such a limit doesn't exist right now.

**Comment by friguzzi** [comment]
thanks for the clarificiation. I agree that it is better to move data to the working module, so I will modify cplint for that. But maybe a limit on thread_local store can be of use for others

**Comment by JanWielemaker** [comment]
> But maybe a limit on thread_local store can be of use for others

It is surely something that should be considered.   Typically these things remain in the pipeline until there is a case that cannot be handled sensibly without :)
