### ISSUE TITLE
Feature request: trace/2

### ISSUE THREAD

**Issue by JeanChristopheRohner** [SWI-Prolog/swish#118]
It would be great to be able to use trace/2 on Swish to filter the output of the tracer; e.g. only showing `exit` or `fail`.

**Comment by JanWielemaker** [comment]
You mean e.g., `trace(p/1, fail)`?  Note that that doesn't filter the tracer.  It is completely distinct from the tracer and instead _wraps_ `p/1` to print a message if the indicated _port_ is passed.   Otherwise it would be nice.  I guess it is possible, but __only__ for user defined predicates.  As trace/2 wraps the implementation, applying it to predicates shared between multiple users would cause printed output for all users :disappointed:

**Comment by JeanChristopheRohner** [comment]
Thanks for responding. Aha, it seems i misunderstood `trace/2` then. I was thinking about some kind of filter functionality when doing `trace, p(X)` in Swish, so that this could be used as a way to show proofs (or to show what clauses fail for a goal).
