### ISSUE TITLE
Adding docs on how to print query results in markdown

### ISSUE THREAD

**Issue by Risto-Stevcev** [SWI-Prolog/swish#126]
This is a really cool project!

I have a question/request for docs on how to print query results in markdown cells. I've tried this so far using [MovieBase](https://pengines.swi-prolog.org/apps/swish/p/MovieBase.pl):

~~~markdown
```eval
:- include("MovieBase").
:- findall(M, released_since(M, 2006), M0), atomics_to_string(M0, ', ', A), format(A).
```
~~~

But I get this output:
```
% ERROR: Sandbox restriction!
% ERROR: Could not derive which predicate may be called fromSearch space too large
```

**Comment by JanWielemaker** [comment]
See https://swish.swi-prolog.org/p/rFjFxcjK.swinb

The problem is with format(A).  The argument is a format string and can be dangerous but as the system doesn't know the format string it tries to derive it to check its safely, but it needs to do too much work.  

P.s. please use https://swish.swi-prolog.org.  That is properly maintained.  The pengines site is a bit outdated.

For questions and discussion, please use the SWI-Prolog Discourse forum.   This is more for bugs.

Happy hacking!
