### ISSUE TITLE
bower not cross platform

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/swish#2]
bower's pretty much not usable on windows.

There's supposedly some install path, but it's so crazy I didn't even try it.

**Comment by JanWielemaker** [comment]
Fixed by https://github.com/SWI-Prolog/swish/#download-as-zip.  This allows running the system quite easily from a current Prolog and the SWISH git repo.  This allows for running local copies and doing development on Windows.  You now only need a non-windows platform for generating the minimised CSS and JS files.  Eventually, we'll probably release SWISH versions as a pack that contains the minimised files.  That is also what we do for [ClioPatria](http://cliopatria.swi-prolog.org/packs/swish)
