### ISSUE TITLE
apply/2 does not work — "arguments insufficiently instantiated"

### ISSUE THREAD

**Issue by SQB** [SWI-Prolog/swish#36]
Using regular SWI-Prolog (6.6.4), the query `?- apply(plus, [1, 2, X]).` is answered with `X = 3.`

However, using SWISH, the same query is greeted with the following message:
```
Arguments are not sufficiently instantiated
Reachable from:
	  swish_trace:swish_call(apply(plus,[1,2,A]))
	  '$swish wrapper'(apply(plus,[1,2,A]),B)
```

**Comment by JanWielemaker** [comment]
The meta-calling behaviour of apply/2 is not understood by the sandboxing library.  It's general purpose analysis hits calling an unknown goal, which causes an instantation error.  The feedback for that still needs to be improved.  As apply/2 is basically deprecated I think I'm not going to invent a work around for this.  Use call(plus, 1, 2, X).

**Comment by psionski** [comment]
I'm having a similar issue with `call` - [this program](https://swish.swi-prolog.org/p/qwdYOaOn.swinb) works on a local installation of SWI Prolog, but not on SWISH ("Arguments are not sufficiently instantiated").

It seems to be related to modules, because if I wrap my `call`s in `@(...,user)`, the SWISH version also works.
