### ISSUE TITLE
storage and saving

### ISSUE THREAD

**Issue by olsky** [SWI-Prolog/swish#38]
Dear all,

could you please hint on notebooks/program saving options?

When I save the notebook with a filename, swish creates encoded folder-file structures under 'stogare' (which is in my swipl home dir), these files are not in clear text. Is there a flag to store it in file with cleartext? I would then place this file under code-repo and commit-update changes.

Can I set the storage to point to the custom folder?

Thank you!

**Comment by JanWielemaker** [comment]
See `lib/storage.pl` and `lib/gitty.pl`.   The latter already deals with two backends, so you can use the interface to plug in your own.    The files are stored in a format that is git-based (and compatible), but the overall structure on top of this is slightly different from git.  Notably it maintains versions of _files_ rather than _trees_.
