### ISSUE TITLE
data urls not working in firefox and chrome

### ISSUE THREAD

**Issue by friguzzi** [SWI-Prolog/swish#88]
data urls seem to be not working anymore in firefox and chrome.
They still work only in safari. So when you want to download a c3 chart, you get nothing.
I think it would be useful to be able to download the svg file

**Comment by JanWielemaker** [comment]
I noticed that.  Seems to be the same as https://github.com/piskelapp/piskel/issues/729

**Comment by JanWielemaker** [comment]
That said, considering the size limitations imposed by some browsers on data URIs it might be wise to keep them on the server and download them the conventional way.  That also allows users to download the result using `curl`, etc.   I'll have a look.

**Comment by JanWielemaker** [comment]
Pushed 6eed5f456d94e17f74c8f59b517e4b22e41c01ad, which keeps the data on the server and uses a normal URL.

**Comment by friguzzi** [comment]
Hi Jan,
did you already update the swish server? It doesn't seem to allow downloads, see e.g.
https://swish.swi-prolog.org/example/rendering.swinb
for the result of the first query (the table)
or
https://swish.swi-prolog.org/example/render_c3.swinb

**Comment by JanWielemaker** [comment]
?  Both work fine.  Not very useful though.  You get a very ugly CSV with a single record holding a complicated Prolog term.  That is how it should be though.  Anyway, the patch is for `r_download/0,1` and does not affect CSV downloading.  Tried on latest FF.

**Comment by JanWielemaker** [comment]
Fixed with df5ebe72e561360487e88921c65b7c6f13692eb0.  Not really pretty, but I doubt there is a real solution at this moment.  The SVG is generated by the browser.  The `download` attribute demands _same origin_, but both `data` and `Blob` URLs are considered CORS.  The only smooth way seems to be to upload the SVG to the server and then download it again ...  That doesn't pass my aesthetic requirements ...

The good news is that you can now select the destination file.

**Comment by friguzzi** [comment]
Thanks, it works fine now.

**Comment by friguzzi** [comment]
Now SLDNF trees can be downloaded again!
http://cplint.eu/example/member.swinb
