### ISSUE TITLE
Failing read/1 eats up some resource?

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/swish#9]
I run

test(X) :- read(X).

and enter non-term data a few times in a row (which evidently results in failure).

SWISH gets stroppy and declares "Too many open queries. Please complete some queries by using |Next|, |Stop| or by closing some queries." - and this even if all the queries have been closed. 

Is there a resource that is not being released?

Best regards,

-- David

**Comment by JanWielemaker** [comment]
Leaking on illegal input is fixed.   The Queens example works reasonably.  Basically, the first RETURN runs the query.  The second confirms Stop, the third runs the query, etc.  If you do this too quickly, returns end up in the wrong element due to timing in the interface, so you send two stops to the pengine which responds on the second by telling it does not exist.  That seems to be as far as you get trying to upset the system this way.  I think that is acceptable.
